name: Calculate Orders

on:
  push:
    branches:
      - main

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Установите зависимости, если они есть

      - name: Run order calculation
        run: python acc.py
